/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 */
#ifndef HIP_EP_RUNTIME_H
#define HIP_EP_RUNTIME_H

#include "hipdnn_ep_errors.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Opaque handle for runtime state
typedef struct RuntimeState RuntimeState;

// Forward declaration for constant registry
typedef struct ConstantRegistry ConstantRegistry;

//==============================================================================
// RuntimeState: Opaque Execution State
//==============================================================================
//
// RuntimeState encapsulates GPU execution resources (stream, library handles,
// model constants). Generated code treats it as opaque void*, runtime library
// owns the internal structure.
//
// Design rationale: Opaque pointer pattern allows runtime to evolve internal
// layout without breaking generated code.
//
// Lifecycle: init -> use -> cleanup (must call in this order)
// Thread safety: Not thread-safe (one inference per state at a time)
//==============================================================================

// Initialize runtime state (creates stream, MIOpen handle, hipBLAS handle,
// uploads constants) Parameters:
//   out_state: Pointer to receive allocated RuntimeState
//   registry: Pointer to ConstantRegistry struct with constant metadata
// Return codes:
//   0 = success
//   1 = allocation failed
//   2 = stream creation failed
//   3 = MIOpen creation failed
//   4 = set stream failed
//   5 = hipBLAS creation failed
//   6 = constant upload failed
int hipdnn_ep_state_init(RuntimeState **out_state,
                         const ConstantRegistry *registry);

// Cleanup runtime state (destroys handles, frees memory)
// Best-effort cleanup - continues even if individual operations fail
// Returns 0 always (best-effort)
int hipdnn_ep_state_cleanup(RuntimeState *state);

// Get GPU stream from state (for passing to HIP operations)
// Returns: hipStream_t cast to void* (NULL on error)
// Ownership: Caller does NOT own stream (destroyed in cleanup)
void *hipdnn_ep_state_get_stream(RuntimeState *state);

// Get buffer from memory pool by index
// Returns: GPU pointer at pool_base + buffer_offsets[index] (NULL on error)
// Ownership: Caller does NOT own pointer (freed in cleanup)
void *hipdnn_ep_get_buffer_from_pool(RuntimeState *state, size_t index);

// Initialize memory pool in runtime state
// Called by generated inference_init after creating RuntimeState
// Parameters:
//   state: Runtime state to initialize pool in
//   pool_size: Total size of memory pool in bytes
//   buffer_offsets: Array of offsets for each buffer
//   num_buffers: Number of buffers
// Returns: 0=success, non-zero=error
int hipdnn_ep_pool_init(RuntimeState *state, size_t pool_size,
                        const size_t *buffer_offsets, size_t num_buffers);

//==============================================================================
// Inference API Types (for generated interface)
//==============================================================================

// Represents a tensor with host data and shape information
typedef struct {
  void *data;     // Host data pointer
  int64_t *shape; // Array of dimension sizes
  size_t rank;    // Number of dimensions
} tensor_t;

// Represents a span of tensors (inputs or outputs)
typedef struct {
  tensor_t *data; // Array of tensors
  size_t count;   // Number of tensors
} span_t;

// Represents a prepared tensor with GPU buffer and metadata
// Used internally by tensor preparation helpers
typedef struct {
  void *gpu_ptr;      // GPU memory (allocated or from pool)
  void *host_ptr;     // Host memory (from tensor_t.data)
  int64_t *shape_ptr; // Shape array (from tensor_t.shape) for memref building
  size_t rank;        // Tensor rank (for validation)
  size_t size_bytes;  // Buffer size
  bool is_pooled;     // Internal: true if from pool, false if allocated
} TensorBuffer;

//==============================================================================
// Constant Management
//==============================================================================

// Constant metadata structure (generated by OnnxToHip pass)
typedef struct {
  const void *cpu_data; // CPU pointer to constant in DLL .data section
  size_t size_bytes;    // Size in bytes
  size_t element_size;  // Element size (4 for float32, 2 for float16, etc.)
  size_t num_elements;  // Number of elements
} ConstantInfo;

// Constant registry structure (generated by OnnxToHip pass)
struct ConstantRegistry {
  const ConstantInfo *constants; // Array of constant descriptors
  size_t count;                  // Number of constants
};

// Upload constant to GPU and store at index
// Precondition: index must be in range [0, num_constants), assigned at
// compile-time Returns: 0=success, negative=error
int hipdnn_ep_constant_upload(RuntimeState *state, int64_t index,
                              const void *data, int64_t size);

// Get GPU pointer for constant at index
// Returns: GPU pointer (NULL if not uploaded or error)
// Ownership: Caller does NOT own pointer (freed in constant_release)
void *hipdnn_ep_constant_get(RuntimeState *state, int64_t index);

// Release GPU memory for constant at index
// Returns: 0=success, non-zero=error
int hipdnn_ep_constant_release(RuntimeState *state, int64_t index);

//==============================================================================
// Tensor Preparation Helpers (allocation-strategy agnostic)
//==============================================================================
//
// These helpers abstract tensor preparation logic (parsing, validation,
// GPU allocation, H2D/D2H transfer) from the generated code.
//
// Design principle: The runtime decides internally whether to use Phase 1
// (per-call allocation) or Phase 2 (hoisted buffers/pool) by changing
// implementation, not interface. Generated code is allocation-strategy
// agnostic.
//
// Element size: Currently assumes float32 (4 bytes). Future: add data_type
// field to tensor_t for multi-dtype support.
//==============================================================================

// Prepare input tensor: parse, validate, get/allocate GPU buffer, H2D transfer
//
// The runtime decides internally whether to:
//   - Allocate fresh buffer (Phase 1: per-call allocation)
//   - Reuse pre-allocated buffer from state (Phase 2: hoisting)
//
// Parameters:
//   state: Runtime state (provides stream, may contain pre-allocated buffers)
//   inputs: Span of input tensors
//   index: Which tensor to prepare (0-based)
//   expected_rank: Compile-time known rank (from module metadata)
//   out_buffer: Output TensorBuffer to populate
//
// Return codes:
//   HIPDNN_EP_SUCCESS (0) = success
//   HIPDNN_EP_ERR_INDEX_OUT_OF_BOUNDS = index >= inputs->count
//   HIPDNN_EP_ERR_RANK_MISMATCH = inputs->data[index].rank != expected_rank
//   HIPDNN_EP_ERR_NULL_POINTER = tensor data or shape is NULL
//   HIPDNN_EP_ERR_INVALID_DIMENSION = shape contains non-positive values
//   HIPDNN_EP_ERR_SIZE_OVERFLOW = total size calculation overflows
//   HIPDNN_EP_ERR_GPU_ALLOC_FAILED = allocation failed or pool exhausted
//   HIPDNN_EP_ERR_H2D_TRANSFER_FAILED = H2D transfer failed
int hipdnn_ep_tensor_prepare_input(RuntimeState *state, span_t *inputs,
                                   size_t index, size_t expected_rank,
                                   TensorBuffer *out_buffer);

// Prepare output tensor: parse, validate, get/allocate GPU buffer (no H2D)
//
// Parameters: same as prepare_input
//
// Return codes: same as prepare_input except H2D error (no transfer)
int hipdnn_ep_tensor_prepare_output(RuntimeState *state, span_t *outputs,
                                    size_t index, size_t expected_rank,
                                    TensorBuffer *out_buffer);

// Finalize output tensor: D2H transfer, sync, release buffer
//
// The runtime decides internally whether to:
//   - Free buffer immediately (Phase 1)
//   - Return buffer to pool for reuse (Phase 2)
//   - Do nothing if buffer is pre-allocated (Phase 2, keep in state)
//
// Parameters:
//   state: Runtime state
//   buffer: TensorBuffer from prepare_output
//
// Return codes:
//   HIPDNN_EP_SUCCESS (0) = success
//   HIPDNN_EP_ERR_D2H_TRANSFER_FAILED = D2H transfer failed
//   HIPDNN_EP_ERR_STREAM_SYNC_FAILED = stream sync failed
//
// Note: Buffer is released even on error (best-effort cleanup)
int hipdnn_ep_tensor_finalize_output(RuntimeState *state, TensorBuffer *buffer);

// Release input tensor buffer (no D2H transfer needed)
//
// The runtime decides whether to free or return to pool
//
// Parameters:
//   state: Runtime state
//   buffer: TensorBuffer from prepare_input
void hipdnn_ep_tensor_free_input(RuntimeState *state, TensorBuffer *buffer);

//==============================================================================
// Library Operations (MIOpen, hipBLAS)
//==============================================================================

// MIOpen convolution forward operation
// Full wrapper with descriptor creation, algorithm finding, workspace
// management Follows opaque RuntimeState pattern - extracts handle/stream
// internally Parameters match generated LLVM IR from HipToLLVM pass
int wrap_miopenConvolutionForward(
    RuntimeState
        *state, // RuntimeState (opaque - extracts handle/stream internally)
    const void *input,   // Input tensor GPU pointer
    int64_t input_n,     // Input batch size
    int64_t input_c,     // Input channels
    int64_t input_h,     // Input height
    int64_t input_w,     // Input width
    const void *weights, // Weights tensor GPU pointer
    int64_t weights_k,   // Output channels (number of filters)
    const void *bias,    // Bias tensor GPU pointer (nullable)
    void *output,        // Output tensor GPU pointer (in-place)
    int64_t output_h,    // Output height
    int64_t output_w,    // Output width
    int64_t kernel_h,    // Kernel height
    int64_t kernel_w,    // Kernel width
    int64_t stride_h,    // Stride height
    int64_t stride_w,    // Stride width
    int64_t pad_top,     // Padding top
    int64_t pad_left,    // Padding left
    int64_t pad_bottom,  // Padding bottom
    int64_t pad_right,   // Padding right
    int64_t dilation_h,  // Dilation height
    int64_t dilation_w,  // Dilation width
    int64_t group);      // Number of groups

// hipBLASLt GEMM operation wrapper
// Called by generated IR for matrix multiplication operations
int wrap_hipblasLtGemm(void *handle, // hipBLASLt handle
                       void *stream, // HIP stream
                       int64_t m, int64_t n, int64_t k,
                       const void *alpha, // Scalar alpha
                       const void *A,     // Matrix A GPU pointer
                       const void *B,     // Matrix B GPU pointer
                       const void *beta,  // Scalar beta
                       void *C);          // Matrix C GPU pointer (in/out)

//==============================================================================
// Low-Level HIP Wrappers
//==============================================================================

// HIP memory allocation wrapper with error handling
int wrap_hipMalloc(void **ptr, int64_t size);

// HIP memory free wrapper with error handling
int wrap_hipFree(void *ptr);

// HIP memory copy host-to-device wrapper
int wrap_hipMemcpyH2D(void *dst, const void *src, int64_t size, void *stream);

// HIP memory copy device-to-host wrapper
int wrap_hipMemcpyD2H(void *dst, const void *src, int64_t size, void *stream);

// HIP stream synchronization wrapper
int wrap_hipStreamSynchronize(void *stream);

#ifdef __cplusplus
}
#endif

#endif // HIP_EP_RUNTIME_H
